name: gotoko
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.4+4

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  shared_preferences: ^2.0.6
  connectivity_plus: ^3.0.2
  firebase_core: ^2.6.1
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^12.0.2
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  image_picker: ^0.8.4+10
  fl_chart: ^0.55.0
  get: ^4.6.3
  flutter_switch: ^0.3.2
  timezone: ^0.9.0
  advance_pdf_viewer: ^2.0.1
  file_picker: ^5.2.2
  barcode_widget: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^10.0.0
  flutter_downloader: ^1.8.0+1
  fluttertoast: ^8.0.9
  provider: ^6.0.5
  maswend_bt_printer: ^0.0.4
  #maswend_pos_printer_platform: ^1.1.0
  maswend_pos_printer_platform: ^1.0.2
  esc_pos_utils: ^1.1.0
#  printing: ^5.9.3
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  flutter_spinkit: ^5.1.0
  typed_data: ^1.3.1
  http_parser: ^4.0.2
  path: ^1.8.2
  http: ^0.13.6
  dropdown_search: ^5.0.6





dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/Ubuntu-Bold.ttf
          weight: 600
        - asset: assets/font/Ubuntu-Light.ttf
          weight: 300